[workspace]
members = [
    "crates/scheduler_core",
    "crates/scheduler_engine",
    "crates/scheduler_storage",
    "crates/scheduler_integrations",
    "crates/scheduler_ui",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["felixLandlord <felix.landlord.nunoo@gmail.com>"]

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
anyhow = "1.0.100"
thiserror = "2.0.17"
chrono = { version = "0.4.42", features = ["serde"] }
rand = "0.9.2"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
dirs = "6.0.0"
# iced = { version = "0.14.0", features = ["tokio", "debug"] }


[package]
name = "office-scheduler"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
scheduler_core = { path = "crates/scheduler_core" }
scheduler_engine = { path = "crates/scheduler_engine" }
scheduler_storage = { path = "crates/scheduler_storage" }
scheduler_integrations = { path = "crates/scheduler_integrations" }
scheduler_ui = { path = "crates/scheduler_ui" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
iced = { version = "0.14.0", features = ["tokio", "debug"] }


[[bin]]
name = "office-scheduler"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
